var d="Hrithik";
var a="Roshan";
var q=d.concat(a) ;
console.log(a,d,q);
var n1= 2;
var n2=5;
var add= n1+n2;
var subtract= n1-n2;
var divide= n1/n2;
var multiply= n1*n2;
console.log(n1,n2,add,subtract,divide,multiply);
